version: "3"
services:


  postgres:
    restart: always
    image: sameersbn/postgresql:9.5-3
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false

      - DB_USER=codersrank
      - DB_PASS=codersrank
      - DB_NAME=codersrank
  api:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    links:
        - postgres:postgres
    depends_on:
      - postgres
